name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Show repo files
        run: |
          pwd
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            django==4.2 \
            djangorestframework==3.14.0 \
            pytest \
            pytest-django

      - name: Run migrations and tests
        working-directory: /home/runner/work/student_pytest
        env:
          DJANGO_SETTINGS_MODULE: student_project.settings
        run: |
          cd student_pytest/student_project
          python manage.py migrate
          pytest -v 
          